# Generated by Django 5.0.6 on 2024-07-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('skill1', models.CharField(max_length=100)),
                ('skill2', models.CharField(max_length=100)),
                ('skill3', models.CharField(max_length=100)),
                ('skill4', models.CharField(max_length=100)),
                ('skill5', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('ytb', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('lang1', models.CharField(max_length=100)),
                ('lang2', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('work1', models.CharField(max_length=100)),
                ('work1_info', models.TextField(max_length=200)),
                ('work2', models.CharField(max_length=100)),
                ('work2_info', models.TextField(max_length=200)),
                ('project1', models.CharField(max_length=100)),
                ('project1_info', models.TextField(max_length=200)),
                ('project2', models.CharField(max_length=100)),
                ('project2_info', models.TextField(max_length=200)),
                ('project3', models.CharField(max_length=100)),
                ('project3_info', models.TextField(max_length=200)),
                ('collegeName', models.CharField(max_length=100)),
                ('college_course', models.TextField(max_length=200)),
                ('schoolName', models.CharField(max_length=100)),
                ('school_info', models.TextField(max_length=200)),
                ('certificate1', models.CharField(max_length=100)),
                ('certificate1_info', models.TextField(max_length=200)),
                ('certificate2', models.CharField(max_length=100)),
                ('certificate2_info', models.TextField(max_length=200)),
            ],
        ),
    ]
