# Generated by Django 5.0.6 on 2024-07-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_remove_resume_phone_resume_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='address',
            field=models.CharField(max_length=150),
        ),
    ]
